runtime: nodejs8
threadsafe: true

skip_files:
- node_modules/
- cli/
- server/test/
- github-health-.*\.json

handlers:
- url: /.*
  script: server.js

deploy:
  provider: gae
  keyfile: github-health-staging-5ed56f9155c0.json
  project: github-health-staging
  default: true
